
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nilesh
 */
public class MarksForm extends javax.swing.JFrame {
    String HU,CAT,STREAM1,STREAM2,PCITY,PAREA;
    public Connection conn;
    public Statement stmt;
    int insertsuccess;
    /**
     * Creates new form MarksForm
     */
    public MarksForm() throws ClassNotFoundException, SQLException {
        Class.forName("com.mysql.jdbc.Driver");
            conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/prs", "root", "nilesh@8101998");
            chkConn();
            stmt = (Statement) conn.createStatement();
        initComponents();
    }
    
    public boolean chkConn(){
        return DBConnect.chkconn(this.conn);
    }
    public boolean chk(int mat,int total,int rank,int cetmat,int cetphy,int cettotal){
        if(mat>100 || mat<0)
	{
		setWarningMsg("Mathematics marks must be between 0 to 100");
                return false;
	}
	
	if(rank<1)
	{
		setWarningMsg("Rank cannot be 0 or negative");
                return false;
	}
				
				
	if(cettotal>200 || cettotal<0)
	{
		setWarningMsg("CET total score must be between 0 to 200");
                return false;
	}
				
				
	if(cetmat>100 || cetmat<0 || ((cetmat%2)==1))
	{
		setWarningMsg("CET Mathematics score must be an even integer ");
                return false;
	}
				
				
	if(cetphy>50 || cetphy<0)
	{
            setWarningMsg("CET Physics score must be between 0 to 50");
            return false;
	}
        return true;
    }
    
    public boolean checkNull(){
        if(mathsc.getText().equals("") || aggper.getText().equals("") || cetrank.getText().equals("") || matcet.getText().equals("") || phycet.getText().equals("") || totcet.getText().equals("") ||
                 HomeU.getSelectedItem().equals("Select") || stream1.getSelectedItem().equals("Select") || prefcity.getSelectedItem().equals("Select") ||
                category.getSelectedItem().equals("Select") || stream2.getSelectedItem().equals("Select") || prefarea.getSelectedItem().equals("Select"))
            return true;
        else
            return false;
    }
    
    public void setWarningMsg(String txt)
    {
        JOptionPane.showMessageDialog(rootPane, txt,"Error",1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mathsc = new javax.swing.JTextField();
        aggper = new javax.swing.JTextField();
        cetrank = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        matcet = new javax.swing.JTextField();
        phycet = new javax.swing.JTextField();
        totcet = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        HomeU = new javax.swing.JComboBox<>();
        stream1 = new javax.swing.JComboBox<>();
        prefcity = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        category = new javax.swing.JComboBox<>();
        stream2 = new javax.swing.JComboBox<>();
        prefarea = new javax.swing.JComboBox<>();
        CloseBtn = new javax.swing.JButton();
        GenerateListBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        ResetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MarksForm");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HSC Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 1, 12))); // NOI18N

        jLabel1.setText("Mathematics");

        jLabel2.setText("Aggregate Percentage");

        jLabel3.setText("CET Rank");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(mathsc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aggper, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cetrank, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mathsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(aggper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cetrank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CET Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jLabel4.setText("Mathematics");

        jLabel5.setText("Physics");

        jLabel6.setText("Total");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phycet, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(matcet)
                    .addComponent(totcet))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(matcet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(phycet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(totcet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jLabel7.setText("Home University");

        jLabel8.setText("Stream 1");

        jLabel9.setText("Preferred City");

        HomeU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Dr Babasaheb Ambedkar Marathwada University", "Swami Ramanand Teerth Marathwada University", "Dr Babasaheb Ambedkar Technology university", "Mumbai University", "North Maharashtra University", "Savitribai Phule Pune University", "Shivaji University", "Sant Gadgebaba Amravati University", "Gondwana University", "SNDT Womens University", "Solapur University", "Nagpur University" }));

        stream1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Mechanical", "Mechanical Sandwich", "Chemical", "Electrical", "Electronics", "Civil", "Production", "Production Sandwich", "Electronics and Telecommunications", "Computer", "Information Technology", "Automobile", "Biotechnology" }));

        prefcity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Mumbai", "Nagpur", "Jalgaon", "Malegaon", "Akola", "Parbhani", "Nashik", "Aurangabad", "Pune", "Chandarpur", "Latur", "Nanded", "Kolhapur", "Solapur", "Gadchiroli", "Yavatmal", "Buldana", "Osmanabad", "Wardha", "Sangli", "Satara", "Washim", "Himgoli" }));
        prefcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prefcityActionPerformed(evt);
            }
        });

        jLabel10.setText("Category");

        jLabel11.setText("Stream 2");

        jLabel12.setText("Preferred Area");

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Open", "OBC", "SC", "ST", "NT-A", "NT-B", "NT-C", "NT-D", "TFWS" }));

        stream2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Mechanical", "Mechanical Sandwich", "Chemical", "Electrical", "Electronics", "Civil", "Production", "Production Sandwich", "Electronics and Telecommunications", "Computer", "Information Technology", "Automobile", "Biotechnology" }));

        prefarea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Camp", "Hadapsar", "Shivaji Nagar", "Pimpri", "Chinchwad", "Nigdi", "Vishrantwadi", "Lohgaon", "Wadgaon", "Kondhwa" }));
        prefarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prefareaActionPerformed(evt);
            }
        });

        CloseBtn.setText("Close");
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });

        GenerateListBtn.setText("Generate Preference List");
        GenerateListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateListBtnActionPerformed(evt);
            }
        });

        ResetBtn.setText("Reset");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(179, 179, 179)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(prefcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(stream1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(63, 63, 63)
                                            .addComponent(HomeU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(119, 119, 119)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(90, 90, 90)
                                            .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel12))
                                            .addGap(50, 50, 50)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(stream2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(prefarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(CloseBtn)
                        .addGap(300, 300, 300)
                        .addComponent(GenerateListBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ResetBtn)
                        .addGap(79, 79, 79)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(HomeU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(stream1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(stream2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(prefcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(prefarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenerateListBtn)
                    .addComponent(CloseBtn)
                    .addComponent(ResetBtn))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prefcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prefcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prefcityActionPerformed

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void prefareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prefareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prefareaActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
        mathsc.setText("");
	aggper.setText("");
	cetrank.setText("");
	matcet.setText("");
	phycet.setText("");                        
	totcet.setText("");
	HomeU.setSelectedIndex(0);
	stream1.setSelectedIndex(0);
	prefcity.setSelectedIndex(0);
	category.setSelectedIndex(0);
	stream2.setSelectedIndex(0);
	prefarea.setSelectedIndex(0);
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void GenerateListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateListBtnActionPerformed
        // TODO add your handling code here:
        HU = (String) HomeU.getSelectedItem();
	CAT = (String) category.getSelectedItem();
	STREAM1 = (String) stream1.getSelectedItem();
	STREAM2 = (String) stream2.getSelectedItem();
	PCITY = (String) prefcity.getSelectedItem();
	PAREA = (String) prefarea.getSelectedItem();
        	
	int mat=0;
	int cetmat=0;
	int total=0;
	int cettotal=0;
	int rank=1;
	int cetphy=0;
				
	mat= Integer.parseInt(mathsc.getText());
	total= Integer.parseInt(aggper.getText());
	rank= Integer.parseInt(cetrank.getText());
	cetmat= Integer.parseInt(matcet.getText());
	cetphy= Integer.parseInt(phycet.getText());
	cettotal= Integer.parseInt(totcet.getText());
	
	if(!chk(mat,total,rank,cetmat,cetphy,cettotal))
            return;
				
				//codehere
				
	int upper_bound= Integer.parseInt(totcet.getText()) + 25;
	int lower_bound= Integer.parseInt(totcet.getText()) - 15;
	String s1=new String();
	String s2=new String();
				
					
        if(STREAM1.equalsIgnoreCase("Mechanical Sandwich"))
        {
            upper_bound=200;
            lower_bound=0;
        }
				
        if (STREAM1.equalsIgnoreCase("Production Sandwich"))
        {
            upper_bound = 200;
            lower_bound = 0;
        }

        if (STREAM1.equalsIgnoreCase("Mechanical")) {
            s1 = "mech";
        }

        if (STREAM1.equalsIgnoreCase("Mechanical Sandwich")) {
            s1 = "mech_sand";
        }

        if (STREAM1.equalsIgnoreCase("Production Sandwich")) {
            s1 = "prod_sand";
        }

        if (STREAM1.equalsIgnoreCase("Civil")) {
            s1 = "civil";
        }

        if (STREAM1.equalsIgnoreCase("Chemical")) {
            s1 = "chem";
        }

        if (STREAM1.equalsIgnoreCase("Electrical")) {
            s1 = "electrical";
        }

        if (STREAM1.equalsIgnoreCase("Electronics")) {
            s1 = "elex";
        }

        if (STREAM1.equalsIgnoreCase("Computer")) {
            s1 = "COMPS";
        }

        if (STREAM1.equalsIgnoreCase("Information Technology")) {
            s1 = "it";
        }

        if (STREAM1.equalsIgnoreCase("Electronics and Telecommunications")) {
            s1 = "extc";
        }

        if (STREAM1.equalsIgnoreCase("Production")) {
            s1 = "prod";
        }

        if (STREAM1.equalsIgnoreCase("Instrumentation")) {
            s1 = "instru";
        }

        if (STREAM1.equalsIgnoreCase("Automobile")) {
            s1 = "auto";
        }

        if (STREAM1.equalsIgnoreCase("Biotechnoloy")) {
            s1 = "biotech";
        }

        if (STREAM2.equalsIgnoreCase("Mechanical")) {
            s2 = "mech";
        }

        if (STREAM2.equalsIgnoreCase("Civil")) {
            s2 = "civil";
        }

        if (STREAM2.equalsIgnoreCase("Chemical")) {
            s2 = "chem";
        }

        if (STREAM2.equalsIgnoreCase("Electrical")) {
            s2 = "electrical";
        }

        if (STREAM2.equalsIgnoreCase("Electronics")) {
            s2 = "elex";
        }

        if (STREAM2.equalsIgnoreCase("Computer")) {
            s2 = "COMPS";
        }

        if (STREAM2.equalsIgnoreCase("Information Technology")) {
            s2 = "it";
        }

        if (STREAM2.equalsIgnoreCase("Electronics and telecommunications")) {
            s2 = "extc";
        }

        if (STREAM2.equalsIgnoreCase("Production")) {
            s2 = "prod";
        }

        if (STREAM2.equalsIgnoreCase("Instrumentation")) {
            s2 = "instru";
        }

        if (STREAM2.equalsIgnoreCase("Automobile")) {
            s2 = "auto";
        }

        if (STREAM2.equalsIgnoreCase("Biotechnology")) {
            s2 = "biotech";
        }

        if (STREAM2.equalsIgnoreCase("Mechanical Sandwich")) {
            s2 = "mech_sand";
        }

        if (STREAM2.equalsIgnoreCase("Production Sandwich")) {
            s2 = "prod_sand";
        }

        try {
            
            String d1 = "use open;";
            String d2 = "use obc;";
            String d3 = "use sc;";
            String d4 = "use stnt;";
//            String d5 = "use prs;";
            	 
            String strins = "insert into training_set values(" + mat + "," + total + "," + cetmat + "," + cetphy + "," + cettotal + "," + rank + ");";
            stmt.executeUpdate(strins);
          
            if (CAT.equalsIgnoreCase("open")) {
                stmt.execute(d1);
                  System.out.println("Using OPEN");
            }

            if (CAT.equalsIgnoreCase("obc")) {
                stmt.execute(d2);
            }

            if (CAT.equalsIgnoreCase("sc")) {
                stmt.execute(d3);
            }

            if (CAT.equalsIgnoreCase("st") || CAT.equalsIgnoreCase("nt-a") || CAT.equalsIgnoreCase("nt-b") || CAT.equalsIgnoreCase("nt-c")) {
                stmt.execute(d4);
            }
            if (PCITY.equalsIgnoreCase("pune")) {
                System.out.println("Inside PUNE");
                String q1 = "create temporary table temp1 as select a.name,a.choise_code,a.city,a.location,a.placement_factor,b." + s1 + " from college_info a, pune_open2015 b where a.choise_code=b.choise_code AND b." + s1 + " between " + lower_bound + " AND " + upper_bound + ";";
                String q2 = "create temporary table temp2 as select a.name,a.choise_code,a.city,a.location,a.placement_factor,b." + s1 + " from college_info a, pune_open2016 b where a.choise_code=b.choise_code AND b." + s1 + " between " + lower_bound + " AND " + upper_bound + ";";
                String q3 = "create temporary table temp3 as select a.name,a.choise_code,a.city,a.location,a.placement_factor,b." + s2 + " from college_info a, pune_open2015 b where a.choise_code=b.choise_code AND b." + s2 + " between " + lower_bound + " AND " + upper_bound + ";";
                String q4 = "create temporary table temp4 as select a.name,a.choise_code,a.city,a.location,a.placement_factor,b." + s2 + " from college_info a, pune_open2016 b where a.choise_code=b.choise_code AND b." + s2 + " between " + lower_bound + " AND " + upper_bound + ";";
                String q5 = "create temporary table stream1 as select * from temp1 UNION select * from temp2 ORDER BY " + s1 + " DESC;";
                String q6 = "create temporary table stream2 as select * from temp3 UNION select * from temp4 ORDER BY " + s2 + " DESC;";

                String q7 = "alter table stream1 add column cutoff Int;";
                String q8 = "update stream1 set cutoff =" + s1 + "+0;";
                String q9 = "alter table stream1 drop column " + s1 + ";";

                String q10 = "alter table stream2 add column cutoff Int;";
                String q11 = "update stream2 set cutoff =" + s2 + "+0;";
                String q12 = "alter table stream2 drop column " + s2 + ";";

                String q13 = "alter table stream1 add column Branch char(50);";
                String q14 = "alter table stream2 add column Branch char(50);";

                String q15 = "update stream1 set Branch='" + s1 + "' where city='pune';";
                String q16 = "update stream2 set Branch='" + s2 + "' where city='pune';";

                String q17 = "create temporary table stream1_final as select DISTINCT * from stream1;";
                String q18 = "create temporary table stream2_final as select DISTINCT * from stream2;";

                String q19 = "create table final_list as select * from stream1_final UNION select * from stream2_final;";
                String q20 = "drop table final_list";

                stmt.executeUpdate(q1);
                stmt.executeUpdate(q2);
                stmt.executeUpdate(q3);
                stmt.executeUpdate(q4);
                stmt.executeUpdate(q5);
                stmt.executeUpdate(q6);
                stmt.executeUpdate(q7);
                stmt.executeUpdate(q8);
                stmt.executeUpdate(q9);
                stmt.executeUpdate(q10);
                stmt.executeUpdate(q11);
                stmt.executeUpdate(q12);
                stmt.executeUpdate(q13);
                stmt.executeUpdate(q14);
                stmt.executeUpdate(q15);
                stmt.executeUpdate(q16);
                stmt.executeUpdate(q17);
                stmt.executeUpdate(q18);
                stmt.executeUpdate(q19);
                System.out.println("BEFORE create prs.final");
                String str = "create table prs.final as select * from " + CAT.toLowerCase() + ".final_list;";
                insertsuccess =  stmt.executeUpdate(str);
                
                stmt.executeUpdate(q20);
                System.out.println("after prs.final");
                new ListForm().setVisible(true);
                System.out.println("after listformset visible");
            }

            if (PCITY.equalsIgnoreCase("mumbai")) {

                String q1 = "create temporary table temp1 as select a.name,a.choise_code,a.city,a.location,a.placement_factor,b." + s1 + " from college_info a, mumbai_2015 b where a.choise_code=b.choise_code AND b." + s1 + " between " + lower_bound + " AND " + upper_bound + ";";
                String q2 = "create temporary table temp2 as select a.name,a.choise_code,a.city,a.location,a.placement_factor,b." + s1 + " from college_info a, mumbai_2016 b where a.choise_code=b.choise_code AND b." + s1 + " between " + lower_bound + " AND " + upper_bound + ";";
                String q3 = "create temporary table temp3 as select a.name,a.choise_code,a.city,a.location,a.placement_factor,b." + s2 + " from college_info a, mumbai_2015 b where a.choise_code=b.choise_code AND b." + s2 + " between " + lower_bound + " AND " + upper_bound + ";";
                String q4 = "create temporary table temp4 as select a.name,a.choise_code,a.city,a.location,a.placement_factor,b." + s2 + " from college_info a, mumbai_2016 b where a.choise_code=b.choise_code AND b." + s2 + " between " + lower_bound + " AND " + upper_bound + ";";
                String q5 = "create temporary table stream1 as select * from temp1 UNION select * from temp2 ORDER BY " + s1 + " DESC;";
                String q6 = "create temporary table stream2 as select * from temp3 UNION select * from temp4 ORDER BY " + s2 + " DESC;";

                String q7 = "alter table stream1 add column cutoff Int(3);";
                String q8 = "update stream1 set cutoff = " + s1 + "+0;";
                String q9 = "alter table stream1 drop column " + s1 + ";";

                String q10 = "alter table stream2 add column cutoff Int(3);";
                String q11 = "update stream2 set cutoff = " + s2 + "+0;";
                String q12 = "alter table stream2 drop column " + s2 + ";";

                String q13 = "alter table stream1 add column Branch char(50);";
                String q14 = "alter table stream2 add column Branch char(50);";

                String q15 = "update stream1 set Branch='" + s1 + "' where city='Mumbai';";
                String q16 = "update stream2 set Branch='" + s2 + "' where city='Mumbai';";

                String q17 = "create temporary table stream1_final as select DISTINCT * from stream1;";
                String q18 = "create temporary table stream2_final as select DISTINCT * from stream2;";

                String q19 = "create table final_list as select * from stream1_final UNION select * from stream2_final;";
                String q20 = "drop table final_list;";

                stmt.executeUpdate(q1);
                stmt.executeUpdate(q2);
                stmt.executeUpdate(q3);
                stmt.executeUpdate(q4);
                stmt.executeUpdate(q5);
                stmt.executeUpdate(q6);
                stmt.executeUpdate(q7);
                stmt.executeUpdate(q8);
                stmt.executeUpdate(q9);
                stmt.executeUpdate(q10);
                stmt.executeUpdate(q11);
                stmt.executeUpdate(q12);
                stmt.executeUpdate(q13);
                stmt.executeUpdate(q14);
                stmt.executeUpdate(q15);
                stmt.executeUpdate(q16);
                stmt.executeUpdate(q17);
                stmt.executeUpdate(q18);
                System.out.println("before final_list");
                stmt.executeUpdate(q19);
                System.out.println("after final_list");
                String str = "create table prs.final as select * from " + CAT + ".final_list;";
                stmt.executeUpdate(str);
                stmt.executeUpdate(q20);
                
            }

        } catch (Exception e) {
            System.err.println("Cannot connect the database!..");
            e.printStackTrace();
        } 
        finally {

            try {
                System.out.println("Closing the connection..");
                if (conn != null) {
                    try {
                        stmt.close();
                        System.out.println("stmt closed");
                        conn.close();
                        System.out.println("Conn closed");
                    } catch (SQLException ignore) {
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }   
    }//GEN-LAST:event_GenerateListBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MarksForm().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MarksForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(MarksForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseBtn;
    public javax.swing.JButton GenerateListBtn;
    public javax.swing.JComboBox<String> HomeU;
    private javax.swing.JButton ResetBtn;
    public javax.swing.JTextField aggper;
    public javax.swing.JComboBox<String> category;
    public javax.swing.JTextField cetrank;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextField matcet;
    public javax.swing.JTextField mathsc;
    public javax.swing.JTextField phycet;
    public javax.swing.JComboBox<String> prefarea;
    public javax.swing.JComboBox<String> prefcity;
    public javax.swing.JComboBox<String> stream1;
    public javax.swing.JComboBox<String> stream2;
    public javax.swing.JTextField totcet;
    // End of variables declaration//GEN-END:variables
}
