
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nilesh
 */
public class MarksForm extends javax.swing.JFrame {
    String HU,CAT,STREAM1,STREAM2,PCITY,PAREA;
    /**
     * Creates new form MarksForm
     */
    public MarksForm() {
        initComponents();
    }

    public void setWarningMsg(String txt)
    {
        JOptionPane.showMessageDialog(rootPane, txt,"Error",1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MarksForm");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HSC Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 1, 12))); // NOI18N

        jLabel1.setText("Mathematics");

        jLabel2.setText("Aggregate Percentage");

        jLabel3.setText("CET Rank");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CET Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jLabel4.setText("Mathematics");

        jLabel5.setText("Physics");

        jLabel6.setText("Total");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(jTextField4)
                    .addComponent(jTextField6))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jLabel7.setText("Home University");

        jLabel8.setText("Stream 1");

        jLabel9.setText("Preferred City");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Dr Babasaheb Ambedkar Marathwada University", "Swami Ramanand Teerth Marathwada University", "Dr Babasaheb Ambedkar Technology university", "Mumbai University", "North Maharashtra University", "Savitribai Phule Pune University", "Shivaji University", "Sant Gadgebaba Amravati University", "Gondwana University", "SNDT Womens University", "Solapur University", "Nagpur University" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Mechanical", "Mechanical Sandwich", "Chemical", "Electrical", "Electronics", "Civil", "Production", "Production Sandwich", "Electronics and Telecommunications", "Computer", "Information Technology", "Automobile", "Biotechnology" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Mumbai", "Nagpur", "Jalgaon", "Malegaon", "Akola", "Parbhani", "Nashik", "Aurangabad", "Pune", "Chandarpur", "Latur", "Nanded", "Kolhapur", "Solapur", "Gadchiroli", "Yavatmal", "Buldana", "Osmanabad", "Wardha", "Sangli", "Satara", "Washim", "Himgoli" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel10.setText("Category");

        jLabel11.setText("Stream 2");

        jLabel12.setText("Preferred Area");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Open", "OBC", "SC", "ST", "NT-A", "NT-B", "NT-C", "NT-D", "TFWS" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Mechanical", "Mechanical Sandwich", "Chemical", "Electrical", "Electronics", "Civil", "Production", "Production Sandwich", "Electronics and Telecommunications", "Computer", "Information Technology", "Automobile", "Biotechnology" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Camp", "Hadapsar", "Shivaji Nagar", "Pimpri", "Chinchwad", "Nigdi", "Vishrantwadi", "Lohgaon", "Wadgaon", "Kondhwa" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Generate Preference List");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(179, 179, 179)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(63, 63, 63)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(119, 119, 119)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(90, 90, 90)
                                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel12))
                                            .addGap(50, 50, 50)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jButton1)
                        .addGap(300, 300, 300)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(79, 79, 79)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
	jTextField2.setText("");
	jTextField3.setText("");
	jTextField4.setText("");
	jTextField5.setText("");                        
	jTextField6.setText("");
	jComboBox1.setSelectedIndex(0);
	jComboBox2.setSelectedIndex(0);
	jComboBox3.setSelectedIndex(0);
	jComboBox4.setSelectedIndex(0);
	jComboBox5.setSelectedIndex(0);
	jComboBox6.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        HU = (String) jComboBox1.getSelectedItem();
	CAT = (String) jComboBox4.getSelectedItem();
	STREAM1 = (String) jComboBox2.getSelectedItem();
	STREAM2 = (String) jComboBox5.getSelectedItem();
	PCITY = (String) jComboBox3.getSelectedItem();
	PAREA = (String) jComboBox6.getSelectedItem();
        	
	int mat=0;
	int cetmat=0;
	int total=0;
	int cettotal=0;
	int rank=1;
	int cetphy=0;
				
	mat= Integer.parseInt(jTextField1.getText());
	total= Integer.parseInt(jTextField2.getText());
	rank= Integer.parseInt(jTextField3.getText());
	cetmat= Integer.parseInt(jTextField4.getText());
	cetphy= Integer.parseInt(jTextField5.getText());
	cettotal= Integer.parseInt(jTextField6.getText());
	
	if(mat>100 || mat<0)
	{
		setWarningMsg("Mathematics marks must be between 0 to 100");
                return;
	}
	
	if(rank<1)
	{
		setWarningMsg("Rank cannot be 0 or negative");
                return;
	}
				
				
	if(cettotal>200 || cettotal<0)
	{
		setWarningMsg("CET total score must be between 0 to 200");
                return;
	}
				
				
	if(cetmat>100 || cetmat<0 || ((cetmat%2)==1))
	{
		setWarningMsg("CET Mathematics score must be an even integer ");
                return;
	}
				
				
	if(cetphy>50 || cetphy<0)
	{
            setWarningMsg("CET Physics score must be between 0 to 50");
            return;
	}
				
				//codehere
				
	int upper_bound= Integer.parseInt(jTextField6.getText()) + 25;
	int lower_bound= Integer.parseInt(jTextField6.getText()) - 15;
	String s1=new String();
	String s2=new String();
				
					
        if(STREAM1.equalsIgnoreCase("Mechanical Sandwich"))
        {
            upper_bound=200;
            lower_bound=0;
        }
				
        if (STREAM1.equalsIgnoreCase("Production Sandwich"))
        {
            upper_bound = 200;
            lower_bound = 0;
        }

        if (STREAM1.equalsIgnoreCase("Mechanical")) {
            s1 = "mech";
        }

        if (STREAM1.equalsIgnoreCase("Mechanical Sandwich")) {
            s1 = "mech_sand";
        }

        if (STREAM1.equalsIgnoreCase("Production Sandwich")) {
            s1 = "prod_sand";
        }

        if (STREAM1.equalsIgnoreCase("Civil")) {
            s1 = "civil";
        }

        if (STREAM1.equalsIgnoreCase("Chemical")) {
            s1 = "chem";
        }

        if (STREAM1.equalsIgnoreCase("Electrical")) {
            s1 = "electrical";
        }

        if (STREAM1.equalsIgnoreCase("Electronics")) {
            s1 = "elex";
        }

        if (STREAM1.equalsIgnoreCase("Computer")) {
            s1 = "COMPS";
        }

        if (STREAM1.equalsIgnoreCase("Information Technology")) {
            s1 = "it";
        }

        if (STREAM1.equalsIgnoreCase("Electronics and Telecommunications")) {
            s1 = "extc";
        }

        if (STREAM1.equalsIgnoreCase("Production")) {
            s1 = "prod";
        }

        if (STREAM1.equalsIgnoreCase("Instrumentation")) {
            s1 = "instru";
        }

        if (STREAM1.equalsIgnoreCase("Automobile")) {
            s1 = "auto";
        }

        if (STREAM1.equalsIgnoreCase("Biotechnoloy")) {
            s1 = "biotech";
        }

        if (STREAM2.equalsIgnoreCase("Mechanical")) {
            s2 = "mech";
        }

        if (STREAM2.equalsIgnoreCase("Civil")) {
            s2 = "civil";
        }

        if (STREAM2.equalsIgnoreCase("Chemical")) {
            s2 = "chem";
        }

        if (STREAM2.equalsIgnoreCase("Electrical")) {
            s2 = "electrical";
        }

        if (STREAM2.equalsIgnoreCase("Electronics")) {
            s2 = "elex";
        }

        if (STREAM2.equalsIgnoreCase("Computer")) {
            s2 = "COMPS";
        }

        if (STREAM2.equalsIgnoreCase("Information Technology")) {
            s2 = "it";
        }

        if (STREAM2.equalsIgnoreCase("Electronics and telecommunications")) {
            s2 = "extc";
        }

        if (STREAM2.equalsIgnoreCase("Production")) {
            s2 = "prod";
        }

        if (STREAM2.equalsIgnoreCase("Instrumentation")) {
            s2 = "instru";
        }

        if (STREAM2.equalsIgnoreCase("Automobile")) {
            s2 = "auto";
        }

        if (STREAM2.equalsIgnoreCase("Biotechnology")) {
            s2 = "biotech";
        }

        if (STREAM2.equalsIgnoreCase("Mechanical Sandwich")) {
            s2 = "mech_sand";
        }

        if (STREAM2.equalsIgnoreCase("Production Sandwich")) {
            s2 = "prod_sand";
        }

        Connection conn = null;
        Statement stmt = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/prs", "root", "nilesh@8101998");
            stmt = (Statement) conn.createStatement();
            String d1 = "use open;";
            String d2 = "use obc;";
            String d3 = "use sc;";
            String d4 = "use stnt;";
            String d5 = "use prs;";
            	 
            String strins = "insert into training_set values(" + mat + "," + total + "," + cetmat + "," + cetphy + "," + cettotal + "," + rank + ");";
            stmt.executeUpdate(strins);
          
            if (CAT.equalsIgnoreCase("open")) {
                stmt.execute(d1);
                  System.out.println("Using OPEN");
            }

            if (CAT.equalsIgnoreCase("obc")) {
                stmt.execute(d2);
            }

            if (CAT.equalsIgnoreCase("sc")) {
                stmt.execute(d3);
            }

            if (CAT.equalsIgnoreCase("st") || CAT.equalsIgnoreCase("nt-a") || CAT.equalsIgnoreCase("nt-b") || CAT.equalsIgnoreCase("nt-c")) {
                stmt.execute(d4);
            }
            if (PCITY.equalsIgnoreCase("pune")) {
                System.out.println("Inside PUNE");
                String q1 = "create temporary table temp1 as select a.name,a.choise_code,a.city,a.location,a.placement_factor,b." + s1 + " from college_info a, pune_open2015 b where a.choise_code=b.choise_code AND b." + s1 + " between " + lower_bound + " AND " + upper_bound + ";";
                String q2 = "create temporary table temp2 as select a.name,a.choise_code,a.city,a.location,a.placement_factor,b." + s1 + " from college_info a, pune_open2016 b where a.choise_code=b.choise_code AND b." + s1 + " between " + lower_bound + " AND " + upper_bound + ";";
                String q3 = "create temporary table temp3 as select a.name,a.choise_code,a.city,a.location,a.placement_factor,b." + s2 + " from college_info a, pune_open2015 b where a.choise_code=b.choise_code AND b." + s2 + " between " + lower_bound + " AND " + upper_bound + ";";
                String q4 = "create temporary table temp4 as select a.name,a.choise_code,a.city,a.location,a.placement_factor,b." + s2 + " from college_info a, pune_open2016 b where a.choise_code=b.choise_code AND b." + s2 + " between " + lower_bound + " AND " + upper_bound + ";";
                String q5 = "create temporary table stream1 as select * from temp1 UNION select * from temp2 ORDER BY " + s1 + " DESC;";
                String q6 = "create temporary table stream2 as select * from temp3 UNION select * from temp4 ORDER BY " + s2 + " DESC;";

                String q7 = "alter table stream1 add column cutoff Int;";
                String q8 = "update stream1 set cutoff =" + s1 + "+0;";
                String q9 = "alter table stream1 drop column " + s1 + ";";

                String q10 = "alter table stream2 add column cutoff Int;";
                String q11 = "update stream2 set cutoff =" + s2 + "+0;";
                String q12 = "alter table stream2 drop column " + s2 + ";";

                String q13 = "alter table stream1 add column Branch char(50);";
                String q14 = "alter table stream2 add column Branch char(50);";

                String q15 = "update stream1 set Branch='" + s1 + "' where city='pune';";
                String q16 = "update stream2 set Branch='" + s2 + "' where city='pune';";

                String q17 = "create temporary table stream1_final as select DISTINCT * from stream1;";
                String q18 = "create temporary table stream2_final as select DISTINCT * from stream2;";

                String q19 = "create table final_list as select * from stream1_final UNION select * from stream2_final;";
                String q20 = "drop table final_list";

                stmt.executeUpdate(q1);
                stmt.executeUpdate(q2);
                stmt.executeUpdate(q3);
                stmt.executeUpdate(q4);
                stmt.executeUpdate(q5);
                stmt.executeUpdate(q6);
                stmt.executeUpdate(q7);
                stmt.executeUpdate(q8);
                stmt.executeUpdate(q9);
                stmt.executeUpdate(q10);
                stmt.executeUpdate(q11);
                stmt.executeUpdate(q12);
                stmt.executeUpdate(q13);
                stmt.executeUpdate(q14);
                stmt.executeUpdate(q15);
                stmt.executeUpdate(q16);
                stmt.executeUpdate(q17);
                stmt.executeUpdate(q18);
                stmt.executeUpdate(q19);
                System.out.println("BEFORE create prs.final");
                String str = "create table prs.final as select * from " + CAT.toLowerCase() + ".final_list;";
                stmt.executeUpdate(str);
                
                stmt.executeUpdate(q20);
                new ListForm().setVisible(true);
            }

            if (PCITY.equalsIgnoreCase("mumbai")) {

                String q1 = "create temporary table temp1 as select a.name,a.choise_code,a.city,a.location,a.placement_factor,b." + s1 + " from college_info a, mumbai_2015 b where a.choise_code=b.choise_code AND b." + s1 + " between " + lower_bound + " AND " + upper_bound + ";";
                String q2 = "create temporary table temp2 as select a.name,a.choise_code,a.city,a.location,a.placement_factor,b." + s1 + " from college_info a, mumbai_2016 b where a.choise_code=b.choise_code AND b." + s1 + " between " + lower_bound + " AND " + upper_bound + ";";
                String q3 = "create temporary table temp3 as select a.name,a.choise_code,a.city,a.location,a.placement_factor,b." + s2 + " from college_info a, mumbai_2015 b where a.choise_code=b.choise_code AND b." + s2 + " between " + lower_bound + " AND " + upper_bound + ";";
                String q4 = "create temporary table temp4 as select a.name,a.choise_code,a.city,a.location,a.placement_factor,b." + s2 + " from college_info a, mumbai_2016 b where a.choise_code=b.choise_code AND b." + s2 + " between " + lower_bound + " AND " + upper_bound + ";";
                String q5 = "create temporary table stream1 as select * from temp1 UNION select * from temp2 ORDER BY " + s1 + " DESC;";
                String q6 = "create temporary table stream2 as select * from temp3 UNION select * from temp4 ORDER BY " + s2 + " DESC;";

                String q7 = "alter table stream1 add column cutoff Int(3);";
                String q8 = "update stream1 set cutoff = " + s1 + "+0;";
                String q9 = "alter table stream1 drop column " + s1 + ";";

                String q10 = "alter table stream2 add column cutoff Int(3);";
                String q11 = "update stream2 set cutoff = " + s2 + "+0;";
                String q12 = "alter table stream2 drop column " + s2 + ";";

                String q13 = "alter table stream1 add column Branch char(50);";
                String q14 = "alter table stream2 add column Branch char(50);";

                String q15 = "update stream1 set Branch='" + s1 + "' where city='Mumbai';";
                String q16 = "update stream2 set Branch='" + s2 + "' where city='Mumbai';";

                String q17 = "create temporary table stream1_final as select DISTINCT * from stream1;";
                String q18 = "create temporary table stream2_final as select DISTINCT * from stream2;";

                String q19 = "create table final_list as select * from stream1_final UNION select * from stream2_final;";
                String q20 = "drop table final_list;";

                stmt.executeUpdate(q1);
                stmt.executeUpdate(q2);
                stmt.executeUpdate(q3);
                stmt.executeUpdate(q4);
                stmt.executeUpdate(q5);
                stmt.executeUpdate(q6);
                stmt.executeUpdate(q7);
                stmt.executeUpdate(q8);
                stmt.executeUpdate(q9);
                stmt.executeUpdate(q10);
                stmt.executeUpdate(q11);
                stmt.executeUpdate(q12);
                stmt.executeUpdate(q13);
                stmt.executeUpdate(q14);
                stmt.executeUpdate(q15);
                stmt.executeUpdate(q16);
                stmt.executeUpdate(q17);
                stmt.executeUpdate(q18);
                stmt.executeUpdate(q19);

                String str = "create table prs.final as select * from " + CAT + ".final_list;";
                stmt.executeUpdate(str);
                stmt.executeUpdate(q20);
                
            }

        } catch (Exception e) {
            System.err.println("Cannot connect the database!..");
            e.printStackTrace();
        } 
        finally {

            try {
                System.out.println("Closing the connection..");
                if (conn != null) {
                    try {
                        stmt.close();
                        conn.close();
                    } catch (SQLException ignore) {
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }   
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarksForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
